prompt --install
@@application/set_environment.sql
@@application/delete_application.sql
@@application/create_application.sql
@@application/user_interfaces.sql
@@application/shared_components/navigation/lists/navigation_menu.sql
@@application/shared_components/navigation/lists/navigation_bar.sql
@@application/shared_components/navigation/listentry.sql
@@application/shared_components/files/icons_app_icon_512_png.sql
@@application/shared_components/files/icons_app_icon_32_png.sql
@@application/shared_components/files/icons_app_icon_144_rounded_png.sql
@@application/shared_components/files/icons_app_icon_192_png.sql
@@application/shared_components/files/icons_app_icon_256_rounded_png.sql
@@application/shared_components/files/main_cust_css.sql
@@application/shared_components/files/main_cust_js.sql
@@application/shared_components/files/main_cust_min_js.sql
@@application/shared_components/files/main_cust_min_css.sql
@@application/plugin_settings.sql
@@application/shared_components/security/authorizations/administration_rights.sql
@@application/shared_components/navigation/navigation_bar.sql
@@application/shared_components/logic/application_settings.sql
@@application/shared_components/navigation/tabs/standard.sql
@@application/shared_components/navigation/tabs/parent.sql
@@application/shared_components/user_interface/lovs/anrede.sql
@@application/shared_components/user_interface/lovs/anrede_anrede.sql
@@application/shared_components/user_interface/lovs/arbeitsstunden_saetze.sql
@@application/shared_components/user_interface/lovs/arbeitsstunden_saetze_id.sql
@@application/shared_components/user_interface/lovs/arbeits_termine_erstellt_von.sql
@@application/shared_components/user_interface/lovs/arbeits_termine_id.sql
@@application/shared_components/user_interface/lovs/einsatz_teilnehmer_id.sql
@@application/shared_components/user_interface/lovs/einsatz_teilnehmer_nachname.sql
@@application/shared_components/user_interface/lovs/einsatz_termine.sql
@@application/shared_components/user_interface/lovs/holzerwerb_preise_erwerbart.sql
@@application/shared_components/user_interface/lovs/holzwerber_nachname.sql
@@application/shared_components/user_interface/lovs/holzwerber_multi_column.sql
@@application/shared_components/user_interface/lovs/plz_multi_column.sql
@@application/shared_components/user_interface/lovs/preis_multi_column.sql
@@application/shared_components/user_interface/lovs/rechnungen_kopf_betreff.sql
@@application/shared_components/user_interface/lovs/titel.sql
@@application/shared_components/user_interface/lovs/titel_titel.sql
@@application/shared_components/user_interface/lovs/werbeart.sql
@@application/shared_components/user_interface/lovs/wohnort_multi_column.sql
@@application/pages/page_groups.sql
@@application/shared_components/navigation/breadcrumbs/breadcrumb.sql
@@application/shared_components/navigation/breadcrumbentry.sql
@@application/shared_components/user_interface/templates/popuplov.sql
@@application/shared_components/user_interface/themes.sql
@@application/shared_components/user_interface/theme_style.sql
@@application/shared_components/user_interface/theme_files.sql
@@application/shared_components/user_interface/template_opt_groups.sql
@@application/shared_components/user_interface/template_options.sql
@@application/shared_components/globalization/language.sql
@@application/shared_components/logic/build_options.sql
@@application/shared_components/globalization/messages.sql
@@application/shared_components/globalization/dyntranslations.sql
@@application/shared_components/security/authentications/oracle_apex_accounts.sql
@@application/shared_components/data_loads/lade_umsaetze.sql
@@application/user_interfaces/combined_files.sql
@@application/pages/page_00000.sql
@@application/pages/page_00001.sql
@@application/pages/page_00002.sql
@@application/pages/page_00003.sql
@@application/pages/page_00004.sql
@@application/pages/page_00005.sql
@@application/pages/page_00006.sql
@@application/pages/page_00007.sql
@@application/pages/page_00008.sql
@@application/pages/page_00009.sql
@@application/pages/page_00011.sql
@@application/pages/page_00012.sql
@@application/pages/page_00013.sql
@@application/pages/page_00014.sql
@@application/pages/page_00015.sql
@@application/pages/page_00016.sql
@@application/pages/page_00017.sql
@@application/pages/page_00018.sql
@@application/pages/page_00020.sql
@@application/pages/page_00021.sql
@@application/pages/page_00023.sql
@@application/pages/page_00024.sql
@@application/pages/page_00025.sql
@@application/pages/page_00026.sql
@@application/pages/page_00027.sql
@@application/pages/page_00028.sql
@@application/pages/page_00029.sql
@@application/pages/page_00110.sql
@@application/pages/page_00111.sql
@@application/pages/page_00112.sql
@@application/pages/page_00113.sql
@@application/pages/page_00114.sql
@@application/pages/page_09999.sql
@@application/deployment/definition.sql
@@application/deployment/checks.sql
@@application/deployment/buildoptions.sql
@@application/end_environment.sql
