  CREATE OR REPLACE FORCE EDITIONABLE VIEW "V_ARBEITSSTUNDEN" ("ID", "ET_ID", "NACHNAME", "VORNAME", "SATZ_ID", "STUNDENSATZ", "TERMIN_ID", "TERMIN", "STUNDEN", "ERSTATTUNG", "IBAN", "VERWENDUNG", "BEMERKUNG", "ERSTELLT", "ERSTELLT_VON", "GEAENDERT", "GEAENDERT_VON") AS 
  SELECT A.ID ,
         A.ET_ID ,
         ET.NACHNAME ,
         ET.VORNAME ,
         A.SATZ_ID ,
         HS.STUNDENSATZ ,
         A.TERMIN_ID ,
         AT.TERMIN ,
         A.STUNDEN ,
         HS.STUNDENSATZ * A.STUNDEN ERSTATTUNG ,
         ET.IBAN IBAN ,
         'Arbeitseinsatz WG ' || AT.TERMIN VERWENDUNG ,
         A.BEMERKUNG ,
         A.ERSTELLT ,
         A.ERSTELLT_VON ,
         A.GEAENDERT ,
         A.GEAENDERT_VON 
    FROM ARBEITSSTUNDEN A LEFT OUTER JOIN EINSATZ_TEILNEHMER ET
      ON ET.ID=A.ET_ID    LEFT OUTER JOIN ARBEITSSTUNDEN_SAETZE HS
      ON HS.ID=A.SATZ_ID  LEFT OUTER JOIN ARBEITS_TERMINE AT
      ON AT.ID=A.TERMIN_ID;

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "V_HOLZERWERB" ("ID", "RE_NUMMER", "RE_DATUM", "ANREDE", "TITEL", "NAME", "PLZ_ORT", "ORTSTEIL", "STRAS_NUM", "PREIS_ID", "ERWERBART", "MENGE", "PREIS", "GESAMTPREIS", "ERSTELL_DATUM") AS 
  SELECT RK."ID" ,
         RK.ID "RE_NUMMER" ,
 TO_CHAR(RK.RECHNUNGSDATUM, 'DD.MM.YYYY') "RE_DATUM" ,
         AN.ANREDE "ANREDE" ,
         TI.TITEL  "TITEL" ,
         HW.VORNAME || ' ' || HW.NACHNAME "NAME" ,
         PL.PLZ || ' ' || PL.ORT || CASE WHEN PL.ORTSTEIL IS NULL THEN NULL
                                    ELSE ' OT ' || "ORTSTEIL" 
                                    END  "PLZ_ORT" ,
         PL.ORTSTEIL "ORTSTEIL" ,
         HW.STRASSE || ' ' || HW.HAUSNUMMER "STRAS_NUM" ,                                    
         HP.ID "PREIS_ID" ,
         HP.ERWERBART "ERWERBART" ,
         RP.MENGE "MENGE" ,
         HP.FESTMETERPREIS "PREIS" ,
COALESCE(RP.MENGE, 1) * HP.FESTMETERPREIS "GESAMTPREIS" ,
 TO_CHAR(SYSDATE, 'DD.MM.YYYY') "ERSTELL_DATUM"       
    FROM RECHNUNGEN_KOPF RK             LEFT OUTER JOIN RECHNUNGEN_POS RP
      ON RK.ID = RP.RECHNUNG_ID         LEFT OUTER JOIN HOLZERWERB_PREISE HP
      ON HP.ID = RP.HOLZERWERBPREISE_ID LEFT OUTER JOIN HOLZWERBER HW
      ON HW.ID = RK.HOLZWERBER_ID       LEFT OUTER JOIN POSTLEITZAHLEN PL
      ON PL.ID = HW.PLZ_ID              LEFT OUTER JOIN ANREDE AN
      ON AN.ID = HW.ANREDE_ID           LEFT OUTER JOIN TITEL TI
      ON TI.ID = HW.TITEL_ID
ORDER BY RK.ID , HP.ID ASC;

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "V_RECHNUNGEN_KOPF" ("ID", "RE_NUM", "HOLZWERBER_ID", "VORNAME", "NACHNAME", "PLZ", "ORT", "STRASSE", "NR", "RECHNUNGSDATUM", "RECHNUNGSJAHR", "ZAHLUNGSZIEL", "BETREFF", "RECHNUNGSTEXT", "RECHNUNGSUNTERTEXT", "ERSTELLT", "ERSTELLT_VON", "GEAENDERT", "GEAENDERT_VON") AS 
  SELECT   RK.ID,
           RK.ID RE_NUM,
           RK.HOLZWERBER_ID,
           HW.VORNAME,
           HW.NACHNAME,
           PL.PLZ,
           PL.ORT,
           HW.STRASSE,
           HW.HAUSNUMMER NR,
           RK.RECHNUNGSDATUM,
           TO_CHAR(RK.RECHNUNGSDATUM, 'YYYY') RECHNUNGSJAHR,
           RK.ZAHLUNGSZIEL,
           RK.BETREFF,
           RK.RECHNUNGSTEXT,
           RK.RECHNUNGSUNTERTEXT,
           RK.ERSTELLT,
           RK.ERSTELLT_VON,
           RK.GEAENDERT,
           RK.GEAENDERT_VON
      FROM RECHNUNGEN_KOPF RK LEFT JOIN HOLZWERBER HW
        ON HW.ID = RK.HOLZWERBER_ID LEFT JOIN POSTLEITZAHLEN PL
        ON PL.ID = HW.PLZ_ID;

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "V_RECHNUNG_ZAHLUNG_CHECK" ("WERBER_ID", "VORNAME", "NACHNAME", "RECHNUNG_ID", "RECHNUNGSDATUM", "ZAHLUNGSZIEL", "MAX_ZIELDATUM", "ZAHLUNGSEINGANG", "RECHNUNGSBETRAG", "ZAHLUNGBETRAG", "ZAHLFRIST_DIFF", "ZAHLBETRAG_DIFF", "TERMIN_STATUS", "ZAHL_STATUS", "GESAMT_STATUS") AS 
  SELECT "WERBER_ID" ,
         "VORNAME" ,
         "NACHNAME" ,
         "RECHNUNG_ID" , 
         "RECHNUNGSDATUM" , 
         "ZAHLUNGSZIEL" , 
         "MAX_ZIELDATUM" ,
         "ZAHLUNGSEINGANG" , 
         "RECHNUNGSBETRAG" ,
         "ZAHLUNGBETRAG" , 
         "ZAHLFRIST_DIFF" ,         
         "ZAHLBETRAG_DIFF" ,
    CASE WHEN ZAHLFRIST_DIFF  > 0
         THEN 'Rückstand'
         ELSE 'i.O.'
     END TERMIN_STATUS ,
    CASE WHEN ZAHLUNGSEINGANG IS NOT NULL AND ZAHLBETRAG_DIFF > 0
         THEN 'Unterzahlung'
         ELSE 'i.O.'
     END ZAHL_STATUS ,
    CASE WHEN ZAHLUNGSEINGANG IS NOT NULL AND ZAHLUNGBETRAG = RECHNUNGSBETRAG
         THEN 'i.O.'
         ELSE 'Offen'
     END GESAMT_STATUS
   FROM(
      SELECT "WERBER_ID" ,
             "VORNAME" ,
             "NACHNAME" ,
             "RECHNUNG_ID" , 
             "RECHNUNGSDATUM" , 
             "ZAHLUNGSZIEL" , 
             "MAX_ZIELDATUM" ,
             "ZAHLUNGSEINGANG" , 
             "RECHNUNGSBETRAG" ,
             "ZAHLUNGBETRAG" , 
     COALESCE(TO_DATE("ZAHLUNGSEINGANG", 'DD.MM.YYYY'), SYSDATE) - TO_DATE("MAX_ZIELDATUM", 'DD.MM.YYYY') "ZAHLFRIST_DIFF" ,
            ("RECHNUNGSBETRAG" - "ZAHLUNGBETRAG") "ZAHLBETRAG_DIFF" 
      FROM(
      SELECT "RECHNUNG_ID" ,
             "RECHNUNGSDATUM" ,
             "ZAHLUNGSZIEL" ,
             "MAX_ZIELDATUM" ,
             "WERBER_ID" ,
             "VORNAME" ,
             "NACHNAME" ,
         SUM("RECHNUNGSBETRAG") "RECHNUNGSBETRAG"
        FROM( 
          SELECT RP."RECHNUNG_ID" ,
                 RK."RECHNUNGSDATUM" ,
                 RK."ZAHLUNGSZIEL"  ,
                 RK."RECHNUNGSDATUM" + RK."ZAHLUNGSZIEL" "MAX_ZIELDATUM" ,
                 HW.ID "WERBER_ID" ,
                 HW."VORNAME" ,
                 HW."NACHNAME" ,
                 RP."HOLZERWERBPREISE_ID" ,
                 HP."FESTMETERPREIS" "PREIS" ,
        COALESCE(RP."MENGE", 1) "MENGE" ,
                 (HP."FESTMETERPREIS" * COALESCE(RP."MENGE", 1)) "RECHNUNGSBETRAG"
            FROM RECHNUNGEN_KOPF RK           LEFT OUTER JOIN RECHNUNGEN_POS RP 
              ON RK."ID" = RP."RECHNUNG_ID"   LEFT OUTER JOIN HOLZWERBER HW
              ON HW."ID" = RK."HOLZWERBER_ID" LEFT OUTER JOIN HOLZERWERB_PREISE HP
              ON HP."ID" = RP."HOLZERWERBPREISE_ID"
              )
    GROUP BY "RECHNUNG_ID", "VORNAME", "NACHNAME", "RECHNUNGSDATUM", "ZAHLUNGSZIEL", "WERBER_ID", "MAX_ZIELDATUM" 
    ) RECHNUNGEN LEFT OUTER JOIN
    (
      SELECT "RECHNUNG_ID" "Z_RECHNUNG_ID",
             "ZAHLUNGSEINGANG" ,
             "BETRAG" "ZAHLUNGBETRAG" 
        FROM ZAHLUNGSEINGAENGE  
    ) ZAHLUNGEN
    ON RECHNUNGEN."RECHNUNG_ID" = ZAHLUNGEN."Z_RECHNUNG_ID"
);

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "V_UEBEREIN_LAGERB_FA_WG" ("F_VORNAME", "F_NACHNAME", "F_HSH", "F_ANTEIL", "S_VORNAME", "S_NACHNAME", "S_HSH", "S_ANTEIL") AS 
  select f.vorname f_vorname, f.nachname f_nachname, f.hsh f_hsh, f.anteil f_anteil, 
       s.vorname s_vorname, s.nachname s_nachname, s.hsh s_hsh, s.anteil s_anteil from
(
select vorname, nachname, standard_hash(trim(vorname)||trim(nachname), 'MD5') hsh, anteile_in_qm anteil from mitgliederliste_fa
) f join
(
SELECT vorname, nachname, standard_hash(trim(vorname)||trim(nachname), 'MD5') hsh, anteil anteil FROM LAGERBUCH_SCHMIDT
) s on f.hsh=s.hsh;

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "V_UMSAETZE" ("LFDNR", "VALUTADATUM", "BUCHUNGSJAHR", "VORGANG", "EINNAHMEN", "AUSGABEN", "SALDO_NACH_BUCHUNG") AS 
  SELECT ROWNUM "LFDNR" ,
         DATUM "VALUTADATUM",
 TO_CHAR(DATUM, 'YYYY') BUCHUNGSJAHR ,
         VORGANG ,
         EINNAHMEN ,
         AUSGABEN ,
         SALDO_NACH_BUCHUNG
    FROM(
      SELECT VALUTADATUM "DATUM" ,
             BEMERKUNG "VORGANG" ,
        CASE WHEN BETRAG >= 0 THEN BETRAG ELSE 0
             END "EINNAHMEN" ,
        CASE WHEN BETRAG < 0 THEN ABS(BETRAG) ELSE 0
             END "AUSGABEN" , 
             BETRAG ,
             SALDO_NACH_BUCHUNG
        FROM KONTOUMSAETZE
    ORDER BY VALUTADATUM
	);